sudo: false
dist: trusty

language: node_js
node_js:
  - 8

install:
  - npm install
  - npm install --global now

after_success:
  - now --public --no-clipboard --alias masterclass-$TRAVIS_PULL_REQUEST --token $NOW_TOKEN
  - node node_modules/lighthouse-ci/runlighthouse.js https://masterclass-$TRAVIS_PULL_REQUEST.now.sh
